name: llmsr
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - python=3.11.7=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==2.1.0
    - accelerate==0.27.2
    - aioprometheus==23.12.0
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - anyio==4.3.0
    - attrs==23.2.0
    - bitsandbytes==0.42.0
    - blinker==1.7.0
    - cachetools==5.3.2
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cmake==3.28.3
    - contourpy==1.2.0
    - cupy-cuda12x==12.1.0
    - cycler==0.12.1
    - fastapi==0.110.0
    - fastrlock==0.8.2
    - filelock==3.13.1
    - flask==3.0.2
    - flask-cors==4.0.0
    - fonttools==4.49.0
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - grpcio==1.62.0
    - h11==0.14.0
    - httptools==0.6.1
    - huggingface-hub==0.20.3
    - idna==3.6
    - itsdangerous==2.1.2
    - jinja2==3.1.3
    - joblib==1.3.2
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - kiwisolver==1.4.5
    - lit==17.0.6
    - llvmlite==0.42.0
    - markdown==3.5.2
    - markupsafe==2.1.5
    - matplotlib==3.8.3
    - mpmath==1.3.0
    - msgpack==1.0.7
    - networkx==3.2.1
    - ninja==1.11.1.1
    - numba==0.59.0
    - numpy==1.26.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.535.133
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - nvitop==1.3.2
    - orjson==3.9.15
    - packaging==23.2
    - pandas==2.2.1
    - pillow==10.2.0
    - pip==23.3.1
    - protobuf==4.25.3
    - psutil==5.9.8
    - pydantic==2.6.2
    - pydantic-core==2.16.3
    - pynvml==11.5.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - pytz==2024.1
    - pyyaml==6.0.1
    - quantile-python==1.1
    - ray==2.9.3
    - referencing==0.33.0
    - regex==2023.12.25
    - requests==2.31.0
    - rpds-py==0.18.0
    - safetensors==0.4.2
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - setuptools==68.2.2
    - six==1.16.0
    - sniffio==1.3.0
    - starlette==0.36.3
    - sympy==1.12
    - tensorboard==2.16.2
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - termcolor==2.4.0
    - threadpoolctl==3.3.0
    - timeout==0.1.2
    - timeout-decorator==0.5.0
    - tokenizers==0.15.2
    - torch==2.0.1
    - tqdm==4.66.2
    - transformers==4.38.1
    - triton==2.0.0
    - typing-extensions==4.9.0
    - tzdata==2024.1
    - urllib3==2.2.1
    - uvicorn==0.27.1
    - uvloop==0.19.0
    - watchfiles==0.21.0
    - websockets==12.0
    - werkzeug==3.0.1
    - wheel==0.41.2
